exp_name: "qlora_4bit"

stg1:
  steps: 22500
  lr: 5.0e-4
  batch_size: 2
  grad_accum: 2
  warmup: 0.1

sweep: null

stg2:
  steps: 500
  lr: 2.0e-6
  batch_size: 2
  grad_accum: 4
  warmup: 0.05
  early_stopping_patience: 5
  early_stopping_threshold: 0.0
  wer_eval_steps: 50
  wer_eval_samples: 50

qlora: true

lora:
  r: 8
  alpha: 16
  dropout: 0.05
  target_modules: ["q_proj", "v_proj", "k_proj"]

quantization:
  load_in_4bit: true
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: true

lr_schedule: "cosine"

hf_repo_base: "hyan/qwen_speech_base"
hf_repo_stg1: "hyan/qwen_speech_stage1"
hf_repo_ft: "hyan/qwen-speech-ft"

wandb_project: "qwen2vl_speech"
